name: "Check Terraform"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform-check:
    name: "Check Terraform"
    runs-on: hashicorp/terraform
    strategy:
      matrix:
        module: ["ec2_instance"]
    defaults:
      run: 
        working-directory: "${{ matrix.module }}/test"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-west-2

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -input=false