name: "Check Terraform"

env:
  terraform_version: "1.3.7"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform-check:
    name: "Check Terraform"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ "ec2_instance" ]
    defaults:
      run:
        working-directory: "Terraform_modules/${{ matrix.module }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.terraform_version }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validatge
        if: github.event_name == 'pull_request'
        run: terraform validate
