name: "Check Terraform"

env:
  terraform_version: "1.3.7"

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  determine-modules:
    name: "Determine Terraform Modules"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Extract Dirs from Terraform_Modules
        uses: sergeysova/jq-action@v2
        id: get-json
        with:
          cmd: ls ./Terraform_modules/ | jq -R -s -c 'split("\n")[:-1]'
      - name: Pass to Var
        env:
          ECHO_OUTPUT: ${{ steps.get-json.outputs.value }}
        run: |
          echo $ECHO_OUTPUT
          echo "modules=$ECHO_OUTPUT" >> $GITHUB_OUTPUT

  terraform-check:
    name: "Check Terraform"
    runs-on: ubuntu-latest
    needs: determine-modules
    strategy:
      matrix:
        module: ${{ fromJSON(needs.determine-modules.outputs.modules) }}
    defaults:
      run:
        working-directory: "Terraform_modules/${{ matrix.module }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.terraform_version }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

  terraform-docs:
    name: "Update Terraform Docs"
    runs-on: ubuntu-latest
    needs: terraform-check
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Update README files
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          find-dir: "Terraform_modules"
          config-file: "${{ github.workspace }}/.terraform-docs.yml"
          output-method: inject
          git-push: "true"
