name: "Check Terraform"

env:
  terraform_version: "1.3.7"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  determine_modules:
    name: "Discover Modules"
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.list_modules.outputs.modules }}
    steps:
      - name: List Modules
        id: list_modules
        run: |
          MODULES='${{ $(echo $(ls Terraform_modules) }}'
          echo ::set-output name=modules::${MODULES}
  terraform-check:
    name: "Check Terraform"
    runs-on: ubuntu-latest
    needs:
      - determine_modules
    strategy:
      matrix:
        module: ${{ needs.determine_modules.outputs.modules }}
    defaults:
      run:
        working-directory: "Terraform_modules/${{ matrix.module }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.terraform_version }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        if: github.event_name == 'pull_request'
        run: terraform validate
