name: "Check Terraform"

env:
  terraform_version: "1.3.7"

on:
  pull_request:
    branches: main

jobs:
  terraform-check:
    name: "Check Terraform"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ["ec2_instance", "rds_serverless_cluster", "vpc_subnets"]
    defaults:
      run:
        working-directory: "Terraform_modules/${{ matrix.module }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.terraform_version }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

  terraform-docs:
    name: "Update Terraform Docs"
    runs-on: ubuntu-latest
    needs: terraform-check
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Update README files
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          find-dir: "Terraform_modules"
          config-file: "${{ github.workspace }}/.terraform-docs.yml"
          output-method: inject
          git-push: "true"
